# Generated by Django 3.2.16 on 2023-05-03 16:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('accommodation_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_preview', models.TextField()),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('type', models.CharField(max_length=20)),
                ('rooms', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'accommodation',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.TextField()),
            ],
            options={
                'db_table': 'owner',
            },
        ),
        migrations.CreateModel(
            name='UsersApp',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('sex', models.SmallIntegerField()),
                ('phone_number', models.CharField(max_length=16)),
                ('registr', models.SmallIntegerField(default=0)),
                ('sms', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('personal_data', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('cancellation_policy', models.TextField()),
                ('accommodation_id', models.ForeignKey(db_column='accommodation_id', on_delete=django.db.models.deletion.CASCADE, to='api.accommodation')),
            ],
            options={
                'db_table': 'pricing',
            },
        ),
        migrations.CreateModel(
            name='MyToken',
            fields=[
                ('token_id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(blank=True, max_length=40, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='api.usersapp')),
            ],
            options={
                'db_table': 'tokens',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_dates', models.JSONField()),
                ('accommodation_id', models.ForeignKey(db_column='accommodation_id', on_delete=django.db.models.deletion.CASCADE, to='api.accommodation')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.usersapp')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.AddField(
            model_name='accommodation',
            name='owner_id',
            field=models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, to='api.owner'),
        ),
    ]
